### ISSUE TITLE
Q: What is the simplest way to generate a C++ lib to a Go package

### ISSUE THREAD

**Issue by Akagi201** [xlab/cgogen#13]
I want to port WebRTC lib to Go. The source code of WebRTC is C++.

Should I write C wrappers for C++ class in WebRTC's API headers? And then use cgogen to generate the codes?

Or is there a small C++ lib with cgogen demo for me to learn?

**Comment by xlab** [comment]
Hi! I searched for ways to autogenerate C wrappers for C++ code but couldn't find any. This makes me sad, because it forces me to find somebody who already done any C wrapper and use that work, or create my own from scratch, which is very tedious.

For example, there is Box2D https://github.com/erincatto/Box2D, and luckily it doesn't update too frequently. It means that these C wrappers https://github.com/nical/box2d.rs/tree/master/c/src/Box2D/Dynamics still can be used to generate bindings and they won't be outdated. Sometimes authors of good C++ libraries provide and maintain C API.

If I had time, it's actually possible to write some wrapper generator for C++ using LLVM API, but that's another story.

**Comment by xlab** [comment]
Maybe https://github.com/EricssonResearch/openwebrtc?

**Comment by Akagi201** [comment]
@xlab I found one interesting project to generate C header from CPP headers. https://github.com/anttisalonen/cgen

You may have to look.

**Comment by Akagi201** [comment]
PS: I am also interested in building a tool that can auto generate C wrappers for C++ code. Haha. Hope I can make one some day.

**Comment by xlab** [comment]
@Akagi201 Thanks, `cgen` looked very promising but broke my heart again. It fails to parse Box2D headers which are simple as hell. This is actually problem of all Haskell translators —

1. Tries to be as generalised as possible;
2. Fails on almost any real-world case scenario;
3. Can't be patched by any other community because it's Haskell.

:(

**Comment by Akagi201** [comment]
Found another POC here. https://github.com/samanbarghi/CPP2C

**Comment by xlab** [comment]
@Akagi201 Yeah, something like this can be re-written in Go using Clang bindings (300 lines of code lol). Then add some configuration options (currently, the headers and class names are hard-coded) and some prettifying logic. https://github.com/go-clang/v3.9

This CPP2C example, once patched to include proper class names, works fine on Box2D code.
